flask_app/notes/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

from ..forms import NotesReviewForm, SearchForm, UserSearchForm
from ..models import User, Review, Notes
from ..utils import current_time, get_b64_img

import matplotlib
import matplotlib.pyplot as plt
from io import BytesIO
import base64

notes = Blueprint('notes', __name__, static_folder='static', template_folder='templates')

@notes.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()
    user_search_form = UserSearchForm()

    users = User.objects()
    notes = Notes.objects()
    
    lst = []
    for user in users:
        count = 0
        for note in notes:
            if user == note.notetaker:
                count += 1
        lst.append((user, count))
    lst = sorted(lst, key=lambda x: x[1])
    
    size = len(lst)
    contributions = lst[-5:] if size > 4 else lst[:size]
    xdata = [i[0].username for i in contributions]
    ydata = [i[1] for i in contributions]

    matplotlib.use('agg')
    fig, ax = plt.subplots()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['bottom'].set_color('#DDDDDD')
    ax.tick_params(bottom=False, left=False)
    ax.set_axisbelow(True)
    ax.yaxis.grid(True, color='#EEEEEE')
    ax.xaxis.grid(False)
    plt.bar(x=xdata, height=ydata)
    plt.xlabel('Contributors')
    plt.ylabel('Number of Contributions')

    figfile = BytesIO()
    plt.savefig(figfile, format='png')
    figfile.seek(0)
    figdata_png = base64.b64encode(figfile.getvalue())

    if form.validate_on_submit():
        return redirect(url_for("notes.query_results", query=form.search_query.data))
    if user_search_form.validate_on_submit():
        return redirect(url_for("notes.user_detail", username=user_search_form.username.data))

    return render_template("index.html", form=form, plot=figdata_png.decode('utf8'), form1=user_search_form)


@notes.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        class_names = set(Notes.objects(class_name__icontains=query))
        title_names = set(Notes.objects(title__icontains=query))
        results = list(set.union(class_names, title_names))
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("notes.index"))

    return render_template("query.html", results=results)


@notes.route("/notes/<notes_id>", methods=["GET", "POST"])
def notes_detail(notes_id):
    try:
        result = Notes.objects(id=notes_id).first()
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("notes.index"))

    form = NotesReviewForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            class_name=result.class_name,
            notes_id=notes_id,
            notes_title=result.title,
            rating=form.rating.data
        )
        review.save()

        return redirect(request.path)

    reviews = Review.objects(notes_id=notes_id)
    print(reviews)
    pic_string = get_b64_img(result.id)

    return render_template(
        "notes_detail.html", form=form, notes=result, reviews=reviews, pic_string=pic_string
    )


@notes.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)
    notes = Notes.objects(notetaker=user)

    return render_template("user_detail.html", username=username, reviews=reviews, notes=notes, user=user)

@notes.route("/description")
def description():
    return render_template("description.html")

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request, session
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UploadNotesForm
from ..models import User, Notes
from ..utils import current_time

from werkzeug.utils import secure_filename
import pyotp
import qrcode
import qrcode.image.svg as svg
from io import BytesIO

users = Blueprint('users', __name__, static_folder='static', template_folder='templates')


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("notes.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        session['new_username'] = user.username
        user.save()

        return redirect(url_for("users.tfa"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("notes.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.upload"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("notes.index"))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
    )

@users.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():
    notes_form = UploadNotesForm()

    if notes_form.submit_pic.data and notes_form.validate_on_submit():
        img = notes_form.file.data
        filename = secure_filename(img.filename)
        content_type = f'images/{filename[-3:]}'

        notes = Notes(
            notetaker=current_user._get_current_object(),
            title=notes_form.title.data,
            class_name=notes_form.class_name.data,
            date=current_time()
        )
        notes.notes_file.put(img.stream, content_type=content_type)
        
        notes.save()

        return redirect(url_for('users.upload'))

    notes = Notes.objects(notetaker=current_user._get_current_object())

    return render_template(
        "upload.html",
        title="Account",
        notes_form=notes_form,
        notes=notes
    )


@users.route("/qr_code")
def qr_code():
    if 'new_username' not in session:
        return redirect(url_for('main.index'))
    
    user = User.objects(username=session['new_username']).first()
    session.pop('new_username')

    uri = pyotp.totp.TOTP(user.otp_secret).provisioning_uri(name=user.username, issuer_name='CMSC388J-2FA')
    img = qrcode.make(uri, image_factory=svg.SvgPathImage)
    stream = BytesIO()
    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers


@users.route("/tfa")
def tfa():
    if 'new_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h4>Hey, {{ current_user.username }}!</h4>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" class="justify-content-start" method="POST">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <span class="float-right">
                {{ username_form.submit(class="btn btn-outline-success") }}
            </span>
        </form>
    </div>
</div>
<a href="{{ url_for('notes.user_detail', username=current_user.username) }}">
    <h4><strong>See Activity</strong></h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Notes Reviews</title>
    {% endif %}
</head>

<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/description.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            Description:
        </h1>
        <h6>
            A note sharing application that lets users with accounts post, comment, and rate other people's
            notes. Users can search based on class and see the pdfs when looking at note details.
        </h6>
        <b>
            Contributors: Rahul Narla
        </b>
    </div>
</div>

{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('notes.index') }}">Noteshare</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('notes.user_detail', username=current_user.username)}}">
                    Activity
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.upload') }}">
                    Upload
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/" class="d-flex justify-content-start" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search Class") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            <span class="float-right">
                {{ form.submit(class="btn btn-outline-success") }}
            </span>
        </form>
    </div>
</div>

<div class="row">
    <div class="col">
        <form action="/" class="d-flex justify-content-start" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form1.csrf_token }}
            {{ form1.username(class="form-control", placeholder="Username") }}

            {% if form1.username.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form1.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            <span class="float-right">
                {{ form1.submit1(class="btn btn-outline-success") }}
            </span>
        </form>
    </div>
</div>

<div class="container">
    <div class="d-flex justify-content-center">
        <strong>
            Graph of Top Contributors
        </strong>
    </div>
    <div>
        <div class="d-flex justify-content-center">
            <img img src="data:image/png;base64,{{ plot }}"></img>
        </div>
    </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.token.label(class="form-control-label") }}
                {{ form.token(class="form-control form-control-lg") }}

                {% if form.token.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.token.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/notes_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if notes %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        <div class='float-left'>
          <b>Title:</b> {{ notes.title }}
        </div> 
        <div class='float-right'>
          <b>Date:</b> {{ notes.date }}
        </div> 
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Class:</b> {{ notes.class_name }}</li>
          <li class="list-group-item"><b>Written by:</b> {{ notes.notetaker.username }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<iframe class="col-md-12 h-75 d-inline-block" src="data:application/pdf;base64,{{pic_string}}" frameborder="0"></iframe>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('notes.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p></p>
          <span>
            {{ review.content }}
          </span>
          <span class="float-right">
            <strong>Rating: {{ review.rating }}/5</strong>
          </span>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

        {{ form.rating.label }}
        {{ form.rating(class="form-control") }}

        {% if form.rating.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.rating.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="card my-2">
        <div class='card-body'>
            <div class="media-body">
                <h5>
                    <div>
                        <b>Class: </b> {{ result.class_name }}
                    </div>
                    <p></p>
                    <b>Title: </b>
                    <a href="{{ url_for('notes.notes_detail', notes_id=result.id) }}">
                        {{ result.title }}
                    </a> 
                    <div class='float-right'>
                        {{ result.date }}
                    </div>
                </h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/tfa.html
{% extends "header.html" %}
{% block content %}
    <div>
        <h2>Two-Factor Auth Enrollment</h2>
    </div>
    <div>
        This website requires mandatory 2FA enrollment. 
    </div>
    <!-- Registration Form: -->
    <p>
        Use a authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>
    <img src="{{ url_for('users.qr_code') }}" alt="QR Code for 2FA">

    <div>
        When you're done, you can go to the <a href="{{ url_for('users.login') }}">Login page</a>!
    </div>

{% endblock %}

flask_app/templates/upload.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="row">
        <div class="col">
            <form action="" method="post" enctype="multipart/form-data"> 
                {{ notes_form.csrf_token }}
                <div class="form-group">
                    {{ notes_form.class_name.label }}
                    {{ notes_form.class_name(class="form-control") }}
    
                    {% if notes_form.class_name.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in notes_form.class_name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                {{ notes_form.csrf_token }}
                <div class="form-group">
                    {{ notes_form.title.label }}
                    {{ notes_form.title(class="form-control") }}

                    {% if notes_form.title.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in notes_form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ notes_form.file.label }}
                    {{ notes_form.file(class="form-control") }}

                    {% if notes_form.file.errors %}
                    <div class="alert alert-warning" role="alert">
                    {% for error in notes_form.file.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <div>
                    {{ notes_form.submit_pic(class="btn btn-outline-success") }}
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
<div class="row">
    <a class="nav-link" href="{{ url_for('notes.user_detail', username=current_user.username)}}">
        <strong>See Activity</strong>
    </a>
</div>
{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}

{%if user%}

<div class="row">
    <div class="col">
        <h3>{{ username }}'s Activity</h3>
    </div>
</div>
<div class="row">
    <div class="col">
        <h4> Notes <small class="float-right">{{ notes.count() }} notes</small></h4>
        <ul class="border-bottom">
            {% for note in notes %}
            <li class="media border-top">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ note.date }}</small>
                    </span>
                    <strong>
                        Class: <a href="{{ url_for('notes.notes_detail', notes_id=note.get_id()) }}">
                            {{ note.class_name }}
                        </a>
                    </strong>
                    <p>
                        {{ note.title }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
        <h4> Reviews <small class="float-right">{{ reviews.count() }} reviews</small></h4>
        <ul class="border-bottom">
            {% for review in reviews %}
            <li class="media border-top">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ review.date }}</small>
                    </span>
                    <strong>Title: <a href="{{ url_for('notes.notes_detail', notes_id=review.notes_id) }}">
                            {{ review.notes_title }}
                        </a>
                    </strong>
                    <p></p>
                    <span>
                        {{ review.content }}
                    </span>
                    <span class="float-right">
                        <strong>{{ review.rating }}/5</strong>
                    </span>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{%endif%}
{% endblock %}